create database mypythondb;
use mypythondb;
create table emp(id int, name varchar(30), sal int);
insert into emp values(1,'Rohit',2000);
insert into emp values(2,'Dhawan',800);
insert into emp values(3,'Virat',3000);
insert into emp values(4,'Shreyas',500);
insert into emp values(5,'Dhoni',3000);
insert into emp values(6,'Hardik',1500);
insert into emp values(7,'Chahal',700);
insert into emp values(8,'Kuldeep',1800);
insert into emp values(9,'Bumrah',400);
insert into emp values(10,'Zaheer',5000);
insert into emp values(11,'Nehra',6000);
SELECT * FROM mypythondb.emp;
